# Autogenerated wrapper script for RAxML_jll for i686-w64-mingw32
export raxmlHPC, raxmlHPC_AVX, raxmlHPC_MPI, raxmlHPC_MPI_AVX, raxmlHPC_MPI_SSE3, raxmlHPC_PTHREADS, raxmlHPC_PTHREADS_AVX, raxmlHPC_PTHREADS_SSE3, raxmlHPC_SSE3

using MicrosoftMPI_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("RAxML")
JLLWrappers.@declare_executable_product(raxmlHPC)
JLLWrappers.@declare_executable_product(raxmlHPC_AVX)
JLLWrappers.@declare_executable_product(raxmlHPC_MPI)
JLLWrappers.@declare_executable_product(raxmlHPC_MPI_AVX)
JLLWrappers.@declare_executable_product(raxmlHPC_MPI_SSE3)
JLLWrappers.@declare_executable_product(raxmlHPC_PTHREADS)
JLLWrappers.@declare_executable_product(raxmlHPC_PTHREADS_AVX)
JLLWrappers.@declare_executable_product(raxmlHPC_PTHREADS_SSE3)
JLLWrappers.@declare_executable_product(raxmlHPC_SSE3)
function __init__()
    JLLWrappers.@generate_init_header(MicrosoftMPI_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        raxmlHPC,
        "bin\\raxmlHPC.exe",
    )

    JLLWrappers.@init_executable_product(
        raxmlHPC_AVX,
        "bin\\raxmlHPC-AVX.exe",
    )

    JLLWrappers.@init_executable_product(
        raxmlHPC_MPI,
        "bin\\raxmlHPC-MPI.exe",
    )

    JLLWrappers.@init_executable_product(
        raxmlHPC_MPI_AVX,
        "bin\\raxmlHPC-MPI-AVX.exe",
    )

    JLLWrappers.@init_executable_product(
        raxmlHPC_MPI_SSE3,
        "bin\\raxmlHPC-MPI-SSE3.exe",
    )

    JLLWrappers.@init_executable_product(
        raxmlHPC_PTHREADS,
        "bin\\raxmlHPC-PTHREADS.exe",
    )

    JLLWrappers.@init_executable_product(
        raxmlHPC_PTHREADS_AVX,
        "bin\\raxmlHPC-PTHREADS-AVX.exe",
    )

    JLLWrappers.@init_executable_product(
        raxmlHPC_PTHREADS_SSE3,
        "bin\\raxmlHPC-PTHREADS-SSE3.exe",
    )

    JLLWrappers.@init_executable_product(
        raxmlHPC_SSE3,
        "bin\\raxmlHPC-SSE3.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
